ALTER TABLE `users` ADD `totalInfractions` INT( 1 ) NOT NULL DEFAULT '0', ADD `totalWarnings` INT( 1 ) NOT NULL DEFAULT '0', ADD `banned` INT( 1 ) NOT NULL DEFAULT '0';

CREATE TABLE `infraction_log` (
`id` INT( 255 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`username` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ,
`reason` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
`type` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
`addrem` VARCHAR( 3 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
`issuedby` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
`timestamp` TIMESTAMP( 255 ) ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = MYISAM ;
